module.exports = {
  LOGGED_IN: 'AUTH/LOGGED_IN',
  LOGGED_OUT: 'AUTH/LOGGED_OUT',
  SIGNED_UP: 'AUTH/SIGNED_UP',
  RECEIVED_NEW_BALANCE: 'AUTH/RECEIVED_NEW_BALANCE',
  RECEIVED_ACCOUNT_BALANCES: 'AUTH/RECEIVED_ACCOUNT_BALANCES',
  LOADED_ACCOUNTS: 'AUTH/LOADED_ACCOUNTS',
  ADDED_ACCOUNT: 'AUTH/ADDED_ACCOUNT',
  SELECTED_ACCOUNT: 'AUTH/SELECTED_ACCOUNT',
  RECEIVED_TOKEN: 'AUTH/RECEIVED_TOKEN',
  RENAMED_ACCOUNT: 'AUTH/RENAMED_ACCOUNT',
  DELETED_ACCOUNT: 'AUTH/DELETED_ACCOUNT',
};