module.exports = {
  SELECTED_DATE: 'AUTHENTICATED/TIME/SELECTED_DATE',
  SET_WEEK_PAGE_BY_INDEX: 'AUTHENTICATED/TIME/SET_WEEK_PAGE_BY_INDEX',
  SET_DAY_PAGE_BY_INDEX: 'AUTHENTICATED/TIME/SET_DAY_PAGE_BY_INDEX',
};